# Generated by Django 2.2.7 on 2019-11-12 11:17

from django.db import migrations, models
import landing.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date', models.CharField(max_length=20, null=True, verbose_name='Date')),
                ('text', models.TextField(help_text='Enter a brief description of the book', max_length=300)),
                ('pic', models.ImageField(blank=True, null=True, upload_to=landing.models.get_image_path)),
            ],
        ),
    ]
