# Generated by Django 2.2.7 on 2019-11-20 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0006_auto_20191120_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='infotext',
            name='text_align',
            field=models.CharField(default='center', max_length=15),
        ),
        migrations.AddField(
            model_name='infotext',
            name='text_color',
            field=models.CharField(default='black', max_length=50),
        ),
        migrations.AddField(
            model_name='infotext',
            name='text_content',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AddField(
            model_name='infotext',
            name='text_font_size',
            field=models.IntegerField(default=18),
        ),
    ]
