# Generated by Django 2.2.7 on 2019-11-21 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0008_auto_20191120_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='title',
            field=models.TextField(max_length=200),
        ),
    ]
